// Package shim writes the `godot` launcher Sourdot keeps in its bin
// directory. With that directory on PATH, running `godot` anywhere inside a
// tracked project runs the build Sourdot would open that project with --
// which is what lets a C# test runner, a CI script or a terminal pick up the
// right engine without anyone hard-coding a path to one install.
//
// The launcher is a generated script with every tracked project's answer
// baked in, not a program that resolves anything when it runs. It can't
// ask the store: the GUI holds BoltDB's exclusive lock for as long as it's
// open, so a launcher that read it would hang whenever Sourdot was running.
// And it isn't the Sourdot binary under another name, which links GTK and
// WebKit and on Windows is built for the GUI subsystem, so its output would
// never reach the console that ran `godot`. The cost is that the answers
// are a snapshot, so core regenerates the script whenever a resolution
// could have changed.
package shim

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Target is one tracked project's entry in the launcher.
type Target struct {
	Dir string // project root; a launch from here or anywhere under it resolves to this entry

	// Exec is the executable to run, or "" when the project can't launch,
	// in which case Problem says why and the launcher prints it rather
	// than falling back to some other build.
	Exec    string
	Problem string
}

// Table is everything the launcher knows.
type Table struct {
	Projects []Target

	// Default is run outside any Godot project, "" when no default version
	// is set. It is never used for a project -- tracked or not -- because
	// opening a project in a build it didn't ask for is how it ends up
	// irreversibly upgraded.
	Default string
}

// FileName is the launcher's name on goos.
func FileName(goos string) string {
	if goos == "windows" {
		return "godot.cmd"
	}
	return "godot"
}

// Write renders t for goos into binDir, replacing any previous launcher.
// It leaves the file alone when the content is unchanged, since core calls
// this on every project-list refresh. Returns the launcher's path.
func Write(binDir, goos string, t Table) (string, error) {
	path := filepath.Join(binDir, FileName(goos))
	content := Render(goos, t)
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, content) {
		return path, nil
	}

	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return "", err
	}
	// Write-then-rename, so a test runner that starts mid-rewrite runs
	// the old launcher or the new one, never half of each.
	tmp, err := os.CreateTemp(binDir, ".godot-*")
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp.Name()) // no-op once the rename has happened
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Chmod(tmp.Name(), 0o755); err != nil {
		return "", err
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return "", err
	}
	return path, nil
}

// Render produces the launcher script for goos.
func Render(goos string, t Table) []byte {
	if goos == "windows" {
		return renderCmd(t)
	}
	return renderSh(t)
}

const untrackedMsg = "is a Godot project Sourdot isn't tracking -- add it in Sourdot so it knows which version to run"
const noDefaultMsg = "not inside a Godot project, and no default version is set in Sourdot"

// renderSh writes a POSIX sh launcher. It walks up from the project
// directory -- the one after --path if the command names one, else the
// working directory -- and the first tracked project it reaches wins, so a
// project nested inside another resolves to the inner one. Reaching a
// project.godot that isn't tracked stops the walk with an error instead of
// continuing outward to a project that merely contains it.
func renderSh(t Table) []byte {
	var b strings.Builder
	b.WriteString(`#!/bin/sh
# Generated by Sourdot, and rewritten whenever a project, pin or installed
# version changes -- edits made here won't last.
#
# Runs the Godot build Sourdot would open the surrounding project with.

start=.
prev=
for arg in "$@"; do
	[ "$prev" = --path ] && start=$arg
	prev=$arg
done
d=$(cd "$start" 2>/dev/null && pwd -P) || d=$(pwd -P) || exit 1

while :; do
	case $d in
`)
	for _, p := range t.Projects {
		fmt.Fprintf(&b, "\t%s)\n", shQuote(p.Dir))
		if p.Exec != "" {
			fmt.Fprintf(&b, "\t\texec %s \"$@\" ;;\n", shQuote(p.Exec))
		} else {
			fmt.Fprintf(&b, "\t\techo %s >&2\n\t\texit 1 ;;\n", shQuote("godot (sourdot): "+p.Problem))
		}
	}
	b.WriteString(`	esac
	if [ -f "$d/project.godot" ]; then
		echo "godot (sourdot): $d ` + untrackedMsg + `" >&2
		exit 1
	fi
	[ -n "$d" ] || break
	d=${d%/*}
done

`)
	if t.Default != "" {
		fmt.Fprintf(&b, "exec %s \"$@\"\n", shQuote(t.Default))
	} else {
		fmt.Fprintf(&b, "echo %s >&2\nexit 1\n", shQuote("godot (sourdot): "+noDefaultMsg))
	}
	return []byte(b.String())
}

// shQuote single-quotes s for sh. Inside single quotes nothing is special,
// glob characters included, so a quoted case pattern matches literally.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// renderCmd writes the Windows equivalent as a batch file. It walks up
// from the working directory only: batch has no reliable way to pick
// --path's value out of %*, whose splitting treats = , ; as separators.
func renderCmd(t Table) []byte {
	var b strings.Builder
	w := func(line string) { b.WriteString(line + "\r\n") }

	w("@echo off")
	w("rem Generated by Sourdot, and rewritten whenever a project, pin or installed")
	w("rem version changes -- edits made here won't last.")
	w("rem")
	w("rem Runs the Godot build Sourdot would open the surrounding project with.")
	w("setlocal EnableExtensions DisableDelayedExpansion")
	w(`set "d=%CD%"`)
	w(":walk")
	for i, p := range t.Projects {
		w(fmt.Sprintf(`if /I "%%d%%"=="%s" goto p%d`, cmdLiteral(p.Dir), i))
	}
	w(`if exist "%d%\project.godot" goto untracked`)
	w(`for %%I in ("%d%\..") do set "up=%%~fI"`)
	w(`if /I "%up%"=="%d%" goto outside`)
	w(`set "d=%up%"`)
	w("goto walk")

	for i, p := range t.Projects {
		w(fmt.Sprintf(":p%d", i))
		if p.Exec != "" {
			w(fmt.Sprintf(`"%s" %%*`, cmdLiteral(p.Exec)))
			w("exit /b %ERRORLEVEL%")
		} else {
			w(">&2 echo " + cmdEcho("godot (sourdot): "+p.Problem))
			w("exit /b 1")
		}
	}

	w(":untracked")
	w(">&2 echo " + cmdEcho("godot (sourdot): ") + `"%d%" ` + cmdEcho(untrackedMsg))
	w("exit /b 1")
	w(":outside")
	if t.Default != "" {
		w(fmt.Sprintf(`"%s" %%*`, cmdLiteral(t.Default)))
		w("exit /b %ERRORLEVEL%")
	} else {
		w(">&2 echo " + cmdEcho("godot (sourdot): "+noDefaultMsg))
		w("exit /b 1")
	}
	return []byte(b.String())
}

// cmdLiteral escapes s for use inside double quotes in a batch file, where
// % is the only character still expanded.
func cmdLiteral(s string) string {
	return strings.ReplaceAll(s, "%", "%%")
}

// cmdEcho escapes s for an unquoted echo, where the shell operators are
// live too.
func cmdEcho(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '%':
			b.WriteString("%%")
		case '^', '&', '|', '<', '>', '(', ')':
			b.WriteRune('^')
			b.WriteRune(r)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
