package main

import (
	"embed"
	"os"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/logger"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/mac"
	"github.com/wailsapp/wails/v2/pkg/options/windows"

	"github.com/gladelynch/sourdot/internal/applog"
	"github.com/gladelynch/sourdot/internal/platform"
)

// frontend/dist is generated by tools/frontendbuild (see the Makefile), so
// it is gitignored down to a single .gitkeep. The `all:` prefix is what
// makes that work: without it embed skips dot-files, finds the directory
// empty on a fresh clone, and fails the build before the frontend has been
// built once. With it, `go build` and `go vet` always work and a forgotten
// frontend build shows up as an empty window rather than a compile error.
//
//go:embed all:frontend/dist
var assets embed.FS

//go:embed build/appicon.png
var icon []byte

func main() {
	// The log file has to be open before wails.Run, because Wails builds its
	// own default logger the moment options.App is handed over and startup
	// failures are exactly what we most want on disk. That means resolving
	// the config directory here rather than waiting for App.startup; both
	// call sites share platform.ConfigDir, so they agree on the location.
	appLog := openLog()
	defer appLog.Close()

	// Create an instance of the app structure
	app := NewApp(appLog)

	appLog.Printf("Sourdot %s starting (log: %s)", AppVersion, appLog.Path())

	// Create application with options
	err := wails.Run(&options.App{
		Title:             "Sourdot — Godot Version Manager",
		Width:             1024,
		Height:            768,
		MinWidth:          900,
		MinHeight:         600,
		DisableResize:     false,
		Fullscreen:        false,
		Frameless:         false,
		StartHidden:       false,
		HideWindowOnClose: false,
		BackgroundColour:  &options.RGBA{R: 14, G: 16, B: 19, A: 255}, // matches --bg-0
		Assets:            assets,
		Menu:              nil,
		Logger:            appLog,
		LogLevel:          logger.DEBUG,
		OnStartup:         app.startup,
		OnDomReady:        app.domReady,
		OnBeforeClose:     app.beforeClose,
		OnShutdown:        app.shutdown,
		WindowStartState:  options.Normal,
		Bind: []interface{}{
			app,
		},
		// Windows platform specific options
		Windows: &windows.Options{
			WebviewIsTransparent: false,
			WindowIsTranslucent:  false,
			DisableWindowIcon:    false,
			// DisableFramelessWindowDecorations: false,
			WebviewUserDataPath: "",
		},
		// Mac platform specific options
		Mac: &mac.Options{
			TitleBar: &mac.TitleBar{
				TitlebarAppearsTransparent: true,
				HideTitle:                  false,
				HideTitleBar:               false,
				FullSizeContent:            false,
				UseToolbar:                 false,
				HideToolbarSeparator:       true,
			},
			Appearance:           mac.NSAppearanceNameDarkAqua,
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
			About: &mac.AboutInfo{
				Title:   "Sourdot",
				Message: "Godot Engine version & project manager",
				Icon:    icon,
			},
		},
	})

	if err != nil {
		appLog.Errorf("wails.Run: %v", err)
		appLog.Close()
		os.Exit(1)
	}
}

// openLog sets up file logging, degrading to stderr-only rather than
// refusing to start: a user whose config directory is unwritable should
// still get a working app, just without the log to attach to a bug report.
func openLog() *applog.Logger {
	dir, err := platform.ConfigDir()
	if err != nil {
		l := applog.Stderr()
		l.Errorf("no log file: couldn't resolve the config directory: %v", err)
		return l
	}
	l, err := applog.Init(dir)
	if err != nil {
		l = applog.Stderr()
		l.Errorf("no log file: %v", err)
	}
	return l
}
